#!/usr/bin/env node
/**
 * Imports REAL Quran data into the app. Nothing here invents text: it only reshapes a file you provide.
 *
 *   node scripts/import-quran.mjs <ayahs.json> <surahs.json>
 *
 * ayahs.json  — array of { "surah": 2, "ayah": 255, "page": 42, "juz": 3, "text": "..." }
 *               (page = Madinah mushaf page 1..604, text = Uthmani text from a trusted source)
 * surahs.json — array of { "id": 1, "nameAr": "الفاتحة", "ayahCount": 7, "bismillahPre": false }
 *               startPage is derived from the ayahs.
 *
 * Output (overwrites the sample data):
 *   src/data/quran/pages/NNN.json, surahs.json, manifest.json, pageLoaders.ts
 */
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'src/data/quran');
const TOTAL_PAGES = 604;

const [ayahsPath, surahsPath] = process.argv.slice(2);
if (!ayahsPath || !surahsPath) {
  console.error('Usage: node scripts/import-quran.mjs <ayahs.json> <surahs.json>');
  process.exit(1);
}

const fail = (msg) => {
  console.error(`✖ ${msg}`);
  process.exit(1);
};

const ayahs = JSON.parse(readFileSync(ayahsPath, 'utf8'));
const surahsIn = JSON.parse(readFileSync(surahsPath, 'utf8'));
if (!Array.isArray(ayahs) || ayahs.length === 0) fail('ayahs.json must be a non-empty array');
if (!Array.isArray(surahsIn) || surahsIn.length === 0) fail('surahs.json must be a non-empty array');

const seen = new Set();
const byPage = new Map();
for (const a of ayahs) {
  for (const k of ['surah', 'ayah', 'page', 'juz', 'text']) {
    if (a[k] === undefined || a[k] === null || a[k] === '') fail(`ayah missing "${k}": ${JSON.stringify(a)}`);
  }
  if (!Number.isInteger(a.page) || a.page < 1 || a.page > TOTAL_PAGES) fail(`bad page in ${a.surah}:${a.ayah}`);
  const id = `${a.surah}:${a.ayah}`;
  if (seen.has(id)) fail(`duplicate ayah ${id}`);
  seen.add(id);
  if (!byPage.has(a.page)) byPage.set(a.page, { page: a.page, juz: a.juz, ayahs: [] });
  byPage.get(a.page).ayahs.push({ surah: a.surah, ayah: a.ayah, text: a.text });
}

const pageNumbers = [...byPage.keys()].sort((x, y) => x - y);
for (const p of pageNumbers) byPage.get(p).ayahs.sort((x, y) => x.surah - y.surah || x.ayah - y.ayah);

const startPage = new Map();
for (const p of pageNumbers) {
  for (const a of byPage.get(p).ayahs) {
    if (a.ayah === 1 && !startPage.has(a.surah)) startPage.set(a.surah, p);
  }
}

const surahs = surahsIn.map((s) => {
  const sp = startPage.get(s.id);
  if (sp === undefined) fail(`surah ${s.id}: its first ayah is not in ayahs.json`);
  return { id: s.id, nameAr: s.nameAr, ayahCount: s.ayahCount, bismillahPre: !!s.bismillahPre, startPage: sp };
});

const complete = pageNumbers.length === TOTAL_PAGES && pageNumbers.every((p, i) => p === i + 1);

// Replace previous data
mkdirSync(join(out, 'pages'), { recursive: true });
for (const f of readdirSync(join(out, 'pages'))) rmSync(join(out, 'pages', f));
for (const p of pageNumbers) {
  writeFileSync(join(out, 'pages', `${String(p).padStart(3, '0')}.json`), JSON.stringify(byPage.get(p)) + '\n');
}
writeFileSync(join(out, 'surahs.json'), JSON.stringify(surahs, null, 2) + '\n');
writeFileSync(join(out, 'manifest.json'), JSON.stringify({ totalPages: TOTAL_PAGES, pages: pageNumbers, complete, sample: false }, null, 2) + '\n');

const loaders = pageNumbers
  .map((p) => `  ${p}: () => require('./pages/${String(p).padStart(3, '0')}.json'),`)
  .join('\n');
writeFileSync(
  join(out, 'pageLoaders.ts'),
  `/**
 * AUTO-GENERATED by \`npm run data:quran\` (scripts/import-quran.mjs). Do not edit by hand.
 * Metro needs static require() calls, so every bundled page is listed here.
 * Pages are required lazily, only when the reader asks for them.
 */
import type { QuranPageData } from '@/domain/types';

export const pageLoaders: Record<number, () => QuranPageData> = {
${loaders}
};
`,
);

console.log(`✔ ${ayahs.length} ayahs · ${pageNumbers.length} pages · ${surahs.length} surahs · ${complete ? 'COMPLETE mushaf' : 'partial data'}`);
